language: c
os:
        - linux
before_install:
        - sudo apt-get update
          #- sudo apt-get upgrade
        - chmod +x .travis_setup.sh
        - ./.travis_setup.sh
        
install: 


script:
        - chmod +x bootstrap.sh 
        - ./bootstrap.sh 
        - CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib ./configure --enable-python
        - make
        - OMP_NUM_THREADS=4 make check


